// Code generated by protoc-gen-go. DO NOT EDIT.
// source: expert/lang-combat/protos/login/login.proto

package login

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequestData struct {
	EmailOrPhone         string   `protobuf:"bytes,1,opt,name=EmailOrPhone,proto3" json:"EmailOrPhone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequestData) Reset()         { *m = LoginRequestData{} }
func (m *LoginRequestData) String() string { return proto.CompactTextString(m) }
func (*LoginRequestData) ProtoMessage()    {}
func (*LoginRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2a1f8a79770da, []int{0}
}

func (m *LoginRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequestData.Unmarshal(m, b)
}
func (m *LoginRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequestData.Marshal(b, m, deterministic)
}
func (m *LoginRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequestData.Merge(m, src)
}
func (m *LoginRequestData) XXX_Size() int {
	return xxx_messageInfo_LoginRequestData.Size(m)
}
func (m *LoginRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequestData proto.InternalMessageInfo

func (m *LoginRequestData) GetEmailOrPhone() string {
	if m != nil {
		return m.EmailOrPhone
	}
	return ""
}

func (m *LoginRequestData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponseData struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponseData) Reset()         { *m = LoginResponseData{} }
func (m *LoginResponseData) String() string { return proto.CompactTextString(m) }
func (*LoginResponseData) ProtoMessage()    {}
func (*LoginResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2a1f8a79770da, []int{1}
}

func (m *LoginResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponseData.Unmarshal(m, b)
}
func (m *LoginResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponseData.Marshal(b, m, deterministic)
}
func (m *LoginResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponseData.Merge(m, src)
}
func (m *LoginResponseData) XXX_Size() int {
	return xxx_messageInfo_LoginResponseData.Size(m)
}
func (m *LoginResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponseData proto.InternalMessageInfo

func (m *LoginResponseData) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *LoginResponseData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type LoginRequest struct {
	LoginRequestData     *LoginRequestData `protobuf:"bytes,1,opt,name=loginRequestData,proto3" json:"loginRequestData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2a1f8a79770da, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLoginRequestData() *LoginRequestData {
	if m != nil {
		return m.LoginRequestData
	}
	return nil
}

type LoginResponse struct {
	LoginResponseData    *LoginResponseData `protobuf:"bytes,1,opt,name=loginResponseData,proto3" json:"loginResponseData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2a1f8a79770da, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetLoginResponseData() *LoginResponseData {
	if m != nil {
		return m.LoginResponseData
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequestData)(nil), "login.LoginRequestData")
	proto.RegisterType((*LoginResponseData)(nil), "login.LoginResponseData")
	proto.RegisterType((*LoginRequest)(nil), "login.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "login.LoginResponse")
}

func init() {
	proto.RegisterFile("expert/lang-combat/protos/login/login.proto", fileDescriptor_56d2a1f8a79770da)
}

var fileDescriptor_56d2a1f8a79770da = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xad, 0x90, 0xaa, 0x63, 0x85, 0x76, 0x14, 0x0d, 0x3d, 0xc9, 0x9e, 0x04, 0xb1, 0x81,
	0xea, 0x1b, 0xd8, 0x7a, 0x12, 0x2c, 0x9b, 0x83, 0xe7, 0x6d, 0x1c, 0x6a, 0x60, 0x9b, 0x8d, 0x3b,
	0x1b, 0xf5, 0xf1, 0xc5, 0xe9, 0xfa, 0x27, 0x69, 0x2f, 0xcb, 0xfe, 0x66, 0x98, 0x8f, 0x6f, 0x18,
	0xb8, 0xa6, 0xcf, 0x9a, 0x7c, 0xc8, 0xac, 0xa9, 0x56, 0x37, 0x85, 0x5b, 0x2f, 0x4d, 0xc8, 0x6a,
	0xef, 0x82, 0xe3, 0xcc, 0xba, 0x55, 0x59, 0x6d, 0xde, 0x89, 0x94, 0x30, 0x91, 0xa0, 0x34, 0x0c,
	0x1f, 0xbf, 0x3f, 0x9a, 0xde, 0x1a, 0xe2, 0x30, 0x33, 0xc1, 0xa0, 0x82, 0xc1, 0x7c, 0x6d, 0x4a,
	0xfb, 0xe4, 0x17, 0xaf, 0xae, 0xa2, 0xb4, 0x77, 0xd9, 0xbb, 0x3a, 0xd2, 0xad, 0x1a, 0x8e, 0xe1,
	0x70, 0x61, 0x98, 0x3f, 0x9c, 0x7f, 0x49, 0xf7, 0xa5, 0xff, 0x9b, 0xd5, 0x1c, 0x46, 0x91, 0xc9,
	0xb5, 0xab, 0x98, 0x04, 0x9a, 0xc2, 0x41, 0xde, 0x14, 0x05, 0x31, 0x47, 0xde, 0x4f, 0xc4, 0x73,
	0xe8, 0xe7, 0xc1, 0x84, 0x86, 0x05, 0x94, 0xe8, 0x98, 0x54, 0x0e, 0x83, 0xff, 0x6a, 0x78, 0x0f,
	0x43, 0xdb, 0x51, 0x15, 0xd4, 0xf1, 0xf4, 0x62, 0xb2, 0xd9, 0xac, 0xbb, 0x89, 0xde, 0x1a, 0x50,
	0xcf, 0x70, 0xd2, 0x72, 0xc3, 0x07, 0x18, 0xd9, 0xae, 0x6c, 0xc4, 0xa6, 0x6d, 0xec, 0x5f, 0x5f,
	0x6f, 0x8f, 0x4c, 0x67, 0xd1, 0x36, 0x27, 0xff, 0x5e, 0x16, 0x84, 0x77, 0x90, 0x48, 0xc6, 0xd3,
	0x1d, 0x72, 0xe3, 0xb3, 0x5d, 0x68, 0xb5, 0xb7, 0xec, 0xcb, 0x71, 0x6e, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x75, 0xff, 0x36, 0xcb, 0xcb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoginServiceClient(cc *grpc.ClientConn) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/login.LoginService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterLoginServiceServer(s *grpc.Server, srv LoginServiceServer) {
	s.RegisterService(&_LoginService_serviceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/login.LoginService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "login.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expert/lang-combat/protos/login/login.proto",
}
