// Code generated by protoc-gen-go. DO NOT EDIT.
// source: expert/error-handling/proto/error.proto

package errorpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Color int32

const (
	Color_UNKNOWN Color = 0
	Color_RED     Color = 1
	Color_BLUE    Color = 2
	Color_YELLOW  Color = 3
)

var Color_name = map[int32]string{
	0: "UNKNOWN",
	1: "RED",
	2: "BLUE",
	3: "YELLOW",
}

var Color_value = map[string]int32{
	"UNKNOWN": 0,
	"RED":     1,
	"BLUE":    2,
	"YELLOW":  3,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{0}
}

type EvenNumberRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvenNumberRequest) Reset()         { *m = EvenNumberRequest{} }
func (m *EvenNumberRequest) String() string { return proto.CompactTextString(m) }
func (*EvenNumberRequest) ProtoMessage()    {}
func (*EvenNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{0}
}

func (m *EvenNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvenNumberRequest.Unmarshal(m, b)
}
func (m *EvenNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvenNumberRequest.Marshal(b, m, deterministic)
}
func (m *EvenNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvenNumberRequest.Merge(m, src)
}
func (m *EvenNumberRequest) XXX_Size() int {
	return xxx_messageInfo_EvenNumberRequest.Size(m)
}
func (m *EvenNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvenNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvenNumberRequest proto.InternalMessageInfo

func (m *EvenNumberRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Name struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{1}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Name) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Name) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type Data struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color                Color    `protobuf:"varint,2,opt,name=color,proto3,enum=Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Data) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_UNKNOWN
}

type SuccessResponse struct {
	//repeated as data is multiple
	SuccessInfo          []*SuccessResponse_SuccessInfo `protobuf:"bytes,1,rep,name=success_info,json=successInfo,proto3" json:"success_info,omitempty"`
	IsEven               bool                           `protobuf:"varint,2,opt,name=isEven,proto3" json:"isEven,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{3}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetSuccessInfo() []*SuccessResponse_SuccessInfo {
	if m != nil {
		return m.SuccessInfo
	}
	return nil
}

func (m *SuccessResponse) GetIsEven() bool {
	if m != nil {
		return m.IsEven
	}
	return false
}

type SuccessResponse_SuccessInfo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse_SuccessInfo) Reset()         { *m = SuccessResponse_SuccessInfo{} }
func (m *SuccessResponse_SuccessInfo) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse_SuccessInfo) ProtoMessage()    {}
func (*SuccessResponse_SuccessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{3, 0}
}

func (m *SuccessResponse_SuccessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse_SuccessInfo.Unmarshal(m, b)
}
func (m *SuccessResponse_SuccessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse_SuccessInfo.Marshal(b, m, deterministic)
}
func (m *SuccessResponse_SuccessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse_SuccessInfo.Merge(m, src)
}
func (m *SuccessResponse_SuccessInfo) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse_SuccessInfo.Size(m)
}
func (m *SuccessResponse_SuccessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse_SuccessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse_SuccessInfo proto.InternalMessageInfo

func (m *SuccessResponse_SuccessInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SuccessResponse_SuccessInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SuccessResponse_SuccessInfo) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("Color", Color_name, Color_value)
	proto.RegisterType((*EvenNumberRequest)(nil), "EvenNumberRequest")
	proto.RegisterType((*Name)(nil), "Name")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*SuccessResponse)(nil), "SuccessResponse")
	proto.RegisterType((*SuccessResponse_SuccessInfo)(nil), "SuccessResponse.SuccessInfo")
}

func init() {
	proto.RegisterFile("expert/error-handling/proto/error.proto", fileDescriptor_7921540891055c66)
}

var fileDescriptor_7921540891055c66 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x6b, 0xd4, 0x40,
	0x10, 0xc6, 0x4d, 0xef, 0x72, 0xb9, 0x4c, 0x44, 0xe3, 0x22, 0x72, 0xd6, 0x8a, 0x25, 0x2f, 0x16,
	0xc5, 0x14, 0xd2, 0x57, 0xa1, 0x50, 0x1b, 0x50, 0x3c, 0x52, 0xd8, 0x5a, 0x8a, 0x7d, 0x29, 0x7b,
	0xc9, 0x5c, 0x0d, 0x24, 0xbb, 0x71, 0x77, 0x53, 0xfc, 0x0b, 0xfd, 0xbb, 0x64, 0x27, 0x89, 0xca,
	0x89, 0x6f, 0xf9, 0x7e, 0xdf, 0xec, 0x84, 0xf9, 0x66, 0xe0, 0x35, 0xfe, 0xe8, 0x50, 0xdb, 0x63,
	0xd4, 0x5a, 0xe9, 0x77, 0xdf, 0x84, 0xac, 0x9a, 0x5a, 0xde, 0x1d, 0x77, 0x5a, 0x59, 0x35, 0xc0,
	0x94, 0xbe, 0x93, 0xb7, 0xf0, 0x24, 0xbf, 0x47, 0x59, 0xf4, 0xed, 0x06, 0x35, 0xc7, 0xef, 0x3d,
	0x1a, 0xcb, 0x9e, 0xc1, 0x42, 0x12, 0x58, 0x79, 0x87, 0xde, 0x91, 0xcf, 0x47, 0x95, 0x94, 0x30,
	0x2f, 0x44, 0x8b, 0xec, 0x25, 0xc0, 0xb6, 0xd6, 0xc6, 0xde, 0x4a, 0xd1, 0x22, 0xd5, 0x84, 0x3c,
	0x24, 0x42, 0xf6, 0x2b, 0x88, 0xda, 0xba, 0xaa, 0x1a, 0x1c, 0xfc, 0x3d, 0xf2, 0x61, 0x40, 0x54,
	0xf0, 0x02, 0xc2, 0x46, 0x4c, 0xcf, 0x67, 0x64, 0x2f, 0x1d, 0x70, 0x66, 0x72, 0x0a, 0xf3, 0x73,
	0x61, 0x05, 0x7b, 0x0e, 0xf3, 0xdf, 0xed, 0xa3, 0xcc, 0x4f, 0x9d, 0xc9, 0x09, 0xb1, 0x03, 0xf0,
	0x4b, 0xd5, 0x28, 0x4d, 0xad, 0x1f, 0x65, 0x8b, 0xf4, 0x83, 0x53, 0x7c, 0x80, 0xc9, 0x4f, 0x0f,
	0x1e, 0x5f, 0xf6, 0x65, 0x89, 0xc6, 0x70, 0x34, 0x9d, 0x92, 0x06, 0xd9, 0x29, 0x3c, 0x34, 0x03,
	0xba, 0xad, 0xe5, 0x56, 0xad, 0xbc, 0xc3, 0xd9, 0x51, 0x94, 0x1d, 0xa4, 0x3b, 0x75, 0x93, 0xfe,
	0x24, 0xb7, 0x8a, 0x47, 0xe6, 0x8f, 0x70, 0x91, 0xd4, 0xc6, 0x25, 0x45, 0xff, 0x5c, 0xf2, 0x51,
	0xed, 0xdf, 0x40, 0xf4, 0xd7, 0x1b, 0xb6, 0x82, 0xa0, 0x45, 0x63, 0xc4, 0xdd, 0x14, 0xcb, 0x24,
	0x5d, 0x03, 0x63, 0x85, 0xed, 0x0d, 0x35, 0xf0, 0xf9, 0xa8, 0xdc, 0x98, 0x95, 0xb0, 0x82, 0x62,
	0x70, 0x63, 0xba, 0xd9, 0x39, 0xa1, 0x37, 0x27, 0xe0, 0xd3, 0x60, 0x2c, 0x82, 0xe0, 0xaa, 0xf8,
	0x5c, 0x5c, 0x5c, 0x17, 0xf1, 0x03, 0x16, 0xc0, 0x8c, 0xe7, 0xe7, 0xb1, 0xc7, 0x96, 0x30, 0x3f,
	0x5b, 0x5f, 0xe5, 0xf1, 0x1e, 0x03, 0x58, 0x7c, 0xcd, 0xd7, 0xeb, 0x8b, 0xeb, 0x78, 0x96, 0x7d,
	0x81, 0xa7, 0xb9, 0xdb, 0xef, 0xc7, 0x71, 0xe7, 0x97, 0xa8, 0xef, 0xeb, 0x12, 0xd9, 0xfb, 0xff,
	0x70, 0x96, 0xfe, 0xb3, 0xff, 0xfd, 0x78, 0x37, 0x97, 0xb3, 0xf0, 0x26, 0xa0, 0xab, 0xe9, 0x36,
	0x9b, 0x05, 0x1d, 0xce, 0xc9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x5c, 0x24, 0xc8, 0x63,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ErrorHandlingServiceClient is the client API for ErrorHandlingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ErrorHandlingServiceClient interface {
	ErrorHandlingService(ctx context.Context, in *EvenNumberRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type errorHandlingServiceClient struct {
	cc *grpc.ClientConn
}

func NewErrorHandlingServiceClient(cc *grpc.ClientConn) ErrorHandlingServiceClient {
	return &errorHandlingServiceClient{cc}
}

func (c *errorHandlingServiceClient) ErrorHandlingService(ctx context.Context, in *EvenNumberRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/ErrorHandlingService/ErrorHandlingService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ErrorHandlingServiceServer is the server API for ErrorHandlingService service.
type ErrorHandlingServiceServer interface {
	ErrorHandlingService(context.Context, *EvenNumberRequest) (*SuccessResponse, error)
}

func RegisterErrorHandlingServiceServer(s *grpc.Server, srv ErrorHandlingServiceServer) {
	s.RegisterService(&_ErrorHandlingService_serviceDesc, srv)
}

func _ErrorHandlingService_ErrorHandlingService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvenNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErrorHandlingServiceServer).ErrorHandlingService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ErrorHandlingService/ErrorHandlingService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErrorHandlingServiceServer).ErrorHandlingService(ctx, req.(*EvenNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ErrorHandlingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ErrorHandlingService",
	HandlerType: (*ErrorHandlingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ErrorHandlingService",
			Handler:    _ErrorHandlingService_ErrorHandlingService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expert/error-handling/proto/error.proto",
}
