// Code generated by protoc-gen-go. DO NOT EDIT.
// source: expert/error-handling/proto/error.proto

package error

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Color int32

const (
	Color_UNKNOWN Color = 0
	Color_RED     Color = 1
	Color_BLUE    Color = 2
	Color_YELLOW  Color = 3
)

var Color_name = map[int32]string{
	0: "UNKNOWN",
	1: "RED",
	2: "BLUE",
	3: "YELLOW",
}

var Color_value = map[string]int32{
	"UNKNOWN": 0,
	"RED":     1,
	"BLUE":    2,
	"YELLOW":  3,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{0}
}

type EvenNumberRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvenNumberRequest) Reset()         { *m = EvenNumberRequest{} }
func (m *EvenNumberRequest) String() string { return proto.CompactTextString(m) }
func (*EvenNumberRequest) ProtoMessage()    {}
func (*EvenNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{0}
}

func (m *EvenNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvenNumberRequest.Unmarshal(m, b)
}
func (m *EvenNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvenNumberRequest.Marshal(b, m, deterministic)
}
func (m *EvenNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvenNumberRequest.Merge(m, src)
}
func (m *EvenNumberRequest) XXX_Size() int {
	return xxx_messageInfo_EvenNumberRequest.Size(m)
}
func (m *EvenNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvenNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvenNumberRequest proto.InternalMessageInfo

func (m *EvenNumberRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Name struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{1}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Name) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Name) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type Data struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color                Color    `protobuf:"varint,2,opt,name=color,proto3,enum=Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Data) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_UNKNOWN
}

type SuccessResponse struct {
	//repeated as data is multiple
	SuccessInfo          []*SuccessResponse_SuccessInfo `protobuf:"bytes,1,rep,name=success_info,json=successInfo,proto3" json:"success_info,omitempty"`
	IsEven               bool                           `protobuf:"varint,2,opt,name=isEven,proto3" json:"isEven,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{3}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetSuccessInfo() []*SuccessResponse_SuccessInfo {
	if m != nil {
		return m.SuccessInfo
	}
	return nil
}

func (m *SuccessResponse) GetIsEven() bool {
	if m != nil {
		return m.IsEven
	}
	return false
}

type SuccessResponse_SuccessInfo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse_SuccessInfo) Reset()         { *m = SuccessResponse_SuccessInfo{} }
func (m *SuccessResponse_SuccessInfo) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse_SuccessInfo) ProtoMessage()    {}
func (*SuccessResponse_SuccessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7921540891055c66, []int{3, 0}
}

func (m *SuccessResponse_SuccessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse_SuccessInfo.Unmarshal(m, b)
}
func (m *SuccessResponse_SuccessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse_SuccessInfo.Marshal(b, m, deterministic)
}
func (m *SuccessResponse_SuccessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse_SuccessInfo.Merge(m, src)
}
func (m *SuccessResponse_SuccessInfo) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse_SuccessInfo.Size(m)
}
func (m *SuccessResponse_SuccessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse_SuccessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse_SuccessInfo proto.InternalMessageInfo

func (m *SuccessResponse_SuccessInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SuccessResponse_SuccessInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SuccessResponse_SuccessInfo) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("Color", Color_name, Color_value)
	proto.RegisterType((*EvenNumberRequest)(nil), "EvenNumberRequest")
	proto.RegisterType((*Name)(nil), "Name")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*SuccessResponse)(nil), "SuccessResponse")
	proto.RegisterType((*SuccessResponse_SuccessInfo)(nil), "SuccessResponse.SuccessInfo")
}

func init() {
	proto.RegisterFile("expert/error-handling/proto/error.proto", fileDescriptor_7921540891055c66)
}

var fileDescriptor_7921540891055c66 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x5f, 0x8b, 0xda, 0x40,
	0x14, 0xc5, 0x1b, 0xf3, 0x47, 0xbd, 0x29, 0x6d, 0x3a, 0x0f, 0xc5, 0xb6, 0x96, 0x4a, 0x5e, 0x2a,
	0x2d, 0x8d, 0xa0, 0x1f, 0x40, 0x68, 0xcd, 0x43, 0xa9, 0x44, 0x98, 0x22, 0xb2, 0xfb, 0x22, 0x63,
	0x32, 0xba, 0x81, 0x64, 0xc6, 0x9d, 0x99, 0x2c, 0xfb, 0x09, 0xf7, 0x73, 0x2d, 0x73, 0x63, 0x76,
	0x97, 0x7d, 0xcb, 0xf9, 0x9d, 0x7b, 0x6f, 0x38, 0x67, 0xe0, 0x3b, 0xbf, 0x3f, 0x73, 0x65, 0x66,
	0x5c, 0x29, 0xa9, 0x7e, 0xdd, 0x30, 0x51, 0x54, 0xa5, 0x38, 0xcd, 0xce, 0x4a, 0x1a, 0xd9, 0xc2,
	0x04, 0xbf, 0xe3, 0x9f, 0xf0, 0x21, 0xbd, 0xe3, 0x22, 0x6b, 0xea, 0x03, 0x57, 0x94, 0xdf, 0x36,
	0x5c, 0x1b, 0xf2, 0x11, 0x02, 0x81, 0x60, 0xe4, 0x4c, 0x9c, 0xa9, 0x4f, 0x2f, 0x2a, 0xce, 0xc1,
	0xcb, 0x58, 0xcd, 0xc9, 0x57, 0x80, 0x63, 0xa9, 0xb4, 0xd9, 0x0b, 0x56, 0x73, 0x9c, 0x19, 0xd2,
	0x21, 0x12, 0xb4, 0xbf, 0x41, 0x58, 0x97, 0x45, 0x51, 0xf1, 0xd6, 0xef, 0xa1, 0x0f, 0x2d, 0xc2,
	0x81, 0x2f, 0x30, 0xac, 0x58, 0xb7, 0xee, 0xa2, 0x3d, 0xb0, 0xc0, 0x9a, 0xf1, 0x12, 0xbc, 0x15,
	0x33, 0x8c, 0x7c, 0x02, 0xef, 0xe9, 0x7c, 0x38, 0xf7, 0x13, 0x6b, 0x52, 0x44, 0x64, 0x0c, 0x7e,
	0x2e, 0x2b, 0xa9, 0xf0, 0xf4, 0xbb, 0x79, 0x90, 0xfc, 0xb1, 0x8a, 0xb6, 0x30, 0x7e, 0x70, 0xe0,
	0xfd, 0xff, 0x26, 0xcf, 0xb9, 0xd6, 0x94, 0xeb, 0xb3, 0x14, 0x9a, 0x93, 0x25, 0xbc, 0xd5, 0x2d,
	0xda, 0x97, 0xe2, 0x28, 0x47, 0xce, 0xc4, 0x9d, 0x86, 0xf3, 0x71, 0xf2, 0x6a, 0xae, 0xd3, 0x7f,
	0xc5, 0x51, 0xd2, 0x50, 0x3f, 0x0b, 0x5b, 0x49, 0xa9, 0x6d, 0x53, 0xf8, 0xcf, 0x01, 0xbd, 0xa8,
	0xcf, 0xd7, 0x10, 0xbe, 0xd8, 0x21, 0x23, 0xe8, 0xd7, 0x5c, 0x6b, 0x76, 0xea, 0x6a, 0xe9, 0xa4,
	0x3d, 0xa0, 0x0d, 0x33, 0x8d, 0xc6, 0x03, 0x3e, 0xbd, 0x28, 0x1b, 0xb3, 0x60, 0x86, 0x61, 0x0d,
	0x36, 0xa6, 0xcd, 0x4e, 0x11, 0xfd, 0x58, 0x80, 0x8f, 0xc1, 0x48, 0x08, 0xfd, 0x6d, 0xf6, 0x2f,
	0xdb, 0xec, 0xb2, 0xe8, 0x0d, 0xe9, 0x83, 0x4b, 0xd3, 0x55, 0xe4, 0x90, 0x01, 0x78, 0xbf, 0xd7,
	0xdb, 0x34, 0xea, 0x11, 0x80, 0xe0, 0x2a, 0x5d, 0xaf, 0x37, 0xbb, 0xc8, 0x3d, 0x04, 0xf8, 0xae,
	0x8b, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x97, 0x42, 0x5a, 0x02, 0x02, 0x00, 0x00,
}
