// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/heavyload.proto

package heavyload

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeavyLoadData struct {
	Success              string   `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	LoadBinary           int32    `protobuf:"varint,2,opt,name=loadBinary,proto3" json:"loadBinary,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeavyLoadData) Reset()         { *m = HeavyLoadData{} }
func (m *HeavyLoadData) String() string { return proto.CompactTextString(m) }
func (*HeavyLoadData) ProtoMessage()    {}
func (*HeavyLoadData) Descriptor() ([]byte, []int) {
	return fileDescriptor_050cba2a8e8e4337, []int{0}
}

func (m *HeavyLoadData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeavyLoadData.Unmarshal(m, b)
}
func (m *HeavyLoadData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeavyLoadData.Marshal(b, m, deterministic)
}
func (m *HeavyLoadData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeavyLoadData.Merge(m, src)
}
func (m *HeavyLoadData) XXX_Size() int {
	return xxx_messageInfo_HeavyLoadData.Size(m)
}
func (m *HeavyLoadData) XXX_DiscardUnknown() {
	xxx_messageInfo_HeavyLoadData.DiscardUnknown(m)
}

var xxx_messageInfo_HeavyLoadData proto.InternalMessageInfo

func (m *HeavyLoadData) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *HeavyLoadData) GetLoadBinary() int32 {
	if m != nil {
		return m.LoadBinary
	}
	return 0
}

func (m *HeavyLoadData) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type HeavyLoadInsert struct {
	Add                  int32    `protobuf:"varint,1,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeavyLoadInsert) Reset()         { *m = HeavyLoadInsert{} }
func (m *HeavyLoadInsert) String() string { return proto.CompactTextString(m) }
func (*HeavyLoadInsert) ProtoMessage()    {}
func (*HeavyLoadInsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_050cba2a8e8e4337, []int{1}
}

func (m *HeavyLoadInsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeavyLoadInsert.Unmarshal(m, b)
}
func (m *HeavyLoadInsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeavyLoadInsert.Marshal(b, m, deterministic)
}
func (m *HeavyLoadInsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeavyLoadInsert.Merge(m, src)
}
func (m *HeavyLoadInsert) XXX_Size() int {
	return xxx_messageInfo_HeavyLoadInsert.Size(m)
}
func (m *HeavyLoadInsert) XXX_DiscardUnknown() {
	xxx_messageInfo_HeavyLoadInsert.DiscardUnknown(m)
}

var xxx_messageInfo_HeavyLoadInsert proto.InternalMessageInfo

func (m *HeavyLoadInsert) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

type HeavyLoadDataRequest struct {
	ReqLoad              *HeavyLoadInsert `protobuf:"bytes,1,opt,name=req_load,json=reqLoad,proto3" json:"req_load,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HeavyLoadDataRequest) Reset()         { *m = HeavyLoadDataRequest{} }
func (m *HeavyLoadDataRequest) String() string { return proto.CompactTextString(m) }
func (*HeavyLoadDataRequest) ProtoMessage()    {}
func (*HeavyLoadDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_050cba2a8e8e4337, []int{2}
}

func (m *HeavyLoadDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeavyLoadDataRequest.Unmarshal(m, b)
}
func (m *HeavyLoadDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeavyLoadDataRequest.Marshal(b, m, deterministic)
}
func (m *HeavyLoadDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeavyLoadDataRequest.Merge(m, src)
}
func (m *HeavyLoadDataRequest) XXX_Size() int {
	return xxx_messageInfo_HeavyLoadDataRequest.Size(m)
}
func (m *HeavyLoadDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeavyLoadDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeavyLoadDataRequest proto.InternalMessageInfo

func (m *HeavyLoadDataRequest) GetReqLoad() *HeavyLoadInsert {
	if m != nil {
		return m.ReqLoad
	}
	return nil
}

type HeavyLoadDataResponse struct {
	GetLoad              *HeavyLoadData `protobuf:"bytes,1,opt,name=get_load,json=getLoad,proto3" json:"get_load,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HeavyLoadDataResponse) Reset()         { *m = HeavyLoadDataResponse{} }
func (m *HeavyLoadDataResponse) String() string { return proto.CompactTextString(m) }
func (*HeavyLoadDataResponse) ProtoMessage()    {}
func (*HeavyLoadDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_050cba2a8e8e4337, []int{3}
}

func (m *HeavyLoadDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeavyLoadDataResponse.Unmarshal(m, b)
}
func (m *HeavyLoadDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeavyLoadDataResponse.Marshal(b, m, deterministic)
}
func (m *HeavyLoadDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeavyLoadDataResponse.Merge(m, src)
}
func (m *HeavyLoadDataResponse) XXX_Size() int {
	return xxx_messageInfo_HeavyLoadDataResponse.Size(m)
}
func (m *HeavyLoadDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeavyLoadDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeavyLoadDataResponse proto.InternalMessageInfo

func (m *HeavyLoadDataResponse) GetGetLoad() *HeavyLoadData {
	if m != nil {
		return m.GetLoad
	}
	return nil
}

func init() {
	proto.RegisterType((*HeavyLoadData)(nil), "HeavyLoadData")
	proto.RegisterType((*HeavyLoadInsert)(nil), "HeavyLoadInsert")
	proto.RegisterType((*HeavyLoadDataRequest)(nil), "HeavyLoadDataRequest")
	proto.RegisterType((*HeavyLoadDataResponse)(nil), "HeavyLoadDataResponse")
}

func init() { proto.RegisterFile("proto/heavyload.proto", fileDescriptor_050cba2a8e8e4337) }

var fileDescriptor_050cba2a8e8e4337 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0xa9, 0x73, 0x76, 0x9e, 0xa8, 0xe3, 0xb0, 0x52, 0x04, 0x65, 0xd4, 0x97, 0x8a, 0x10,
	0x61, 0x7e, 0x01, 0xd9, 0x7c, 0x50, 0xf0, 0x29, 0x3e, 0x8b, 0x9c, 0xc9, 0x31, 0x0b, 0x92, 0xac,
	0x49, 0x36, 0xd8, 0xb7, 0x97, 0x04, 0x94, 0xb5, 0xf4, 0xed, 0x7e, 0x77, 0x97, 0x5f, 0xfe, 0x1c,
	0x14, 0x6b, 0x67, 0x83, 0x7d, 0xf8, 0x66, 0xda, 0xee, 0x7e, 0x2c, 0x69, 0x91, 0xb8, 0xfa, 0x80,
	0xd3, 0x97, 0xd8, 0x7a, 0xb3, 0xa4, 0x9f, 0x29, 0x10, 0x96, 0x90, 0xfb, 0x8d, 0x52, 0xec, 0x7d,
	0x99, 0xcd, 0xb2, 0xfa, 0x58, 0xfe, 0x21, 0xde, 0x00, 0xc4, 0x87, 0x8b, 0xc6, 0x90, 0xdb, 0x95,
	0x07, 0xb3, 0xac, 0x1e, 0xcb, 0xbd, 0x0e, 0x22, 0x1c, 0x2a, 0xab, 0xb9, 0x1c, 0xa5, 0x49, 0xaa,
	0xab, 0x5b, 0x38, 0xff, 0xd7, 0xbf, 0x1a, 0xcf, 0x2e, 0xe0, 0x14, 0x46, 0xa4, 0x75, 0x92, 0x8f,
	0x65, 0x2c, 0xab, 0x25, 0x5c, 0x74, 0x32, 0x48, 0x6e, 0x37, 0xec, 0x03, 0xde, 0xc3, 0xc4, 0x71,
	0xfb, 0x19, 0xbf, 0x48, 0xeb, 0x27, 0xf3, 0xa9, 0xe8, 0xd9, 0x64, 0xee, 0xb8, 0x8d, 0x58, 0x2d,
	0xa0, 0xe8, 0x49, 0xfc, 0xda, 0x1a, 0xcf, 0x78, 0x07, 0x93, 0x15, 0x87, 0x7d, 0xcb, 0x99, 0xe8,
	0x6e, 0xe6, 0x2b, 0x0e, 0x11, 0xe6, 0x04, 0xd7, 0x9d, 0xc9, 0xd2, 0x9a, 0x40, 0x8d, 0x61, 0xf7,
	0xce, 0x6e, 0xdb, 0x28, 0xc6, 0xa7, 0xfe, 0xb5, 0x0a, 0x31, 0x94, 0xfc, 0xea, 0x52, 0x0c, 0x66,
	0xa9, 0xb3, 0xaf, 0xa3, 0x74, 0xf6, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x7c, 0x6a,
	0xa5, 0x8f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HeavyLoadDataContainerServiceClient is the client API for HeavyLoadDataContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeavyLoadDataContainerServiceClient interface {
	// add stream keyword when use in client side streaming
	HeavyLoadData(ctx context.Context, opts ...grpc.CallOption) (HeavyLoadDataContainerService_HeavyLoadDataClient, error)
}

type heavyLoadDataContainerServiceClient struct {
	cc *grpc.ClientConn
}

func NewHeavyLoadDataContainerServiceClient(cc *grpc.ClientConn) HeavyLoadDataContainerServiceClient {
	return &heavyLoadDataContainerServiceClient{cc}
}

func (c *heavyLoadDataContainerServiceClient) HeavyLoadData(ctx context.Context, opts ...grpc.CallOption) (HeavyLoadDataContainerService_HeavyLoadDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HeavyLoadDataContainerService_serviceDesc.Streams[0], "/HeavyLoadDataContainerService/HeavyLoadData", opts...)
	if err != nil {
		return nil, err
	}
	x := &heavyLoadDataContainerServiceHeavyLoadDataClient{stream}
	return x, nil
}

type HeavyLoadDataContainerService_HeavyLoadDataClient interface {
	Send(*HeavyLoadDataRequest) error
	CloseAndRecv() (*HeavyLoadDataResponse, error)
	grpc.ClientStream
}

type heavyLoadDataContainerServiceHeavyLoadDataClient struct {
	grpc.ClientStream
}

func (x *heavyLoadDataContainerServiceHeavyLoadDataClient) Send(m *HeavyLoadDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *heavyLoadDataContainerServiceHeavyLoadDataClient) CloseAndRecv() (*HeavyLoadDataResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HeavyLoadDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HeavyLoadDataContainerServiceServer is the server API for HeavyLoadDataContainerService service.
type HeavyLoadDataContainerServiceServer interface {
	// add stream keyword when use in client side streaming
	HeavyLoadData(HeavyLoadDataContainerService_HeavyLoadDataServer) error
}

func RegisterHeavyLoadDataContainerServiceServer(s *grpc.Server, srv HeavyLoadDataContainerServiceServer) {
	s.RegisterService(&_HeavyLoadDataContainerService_serviceDesc, srv)
}

func _HeavyLoadDataContainerService_HeavyLoadData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HeavyLoadDataContainerServiceServer).HeavyLoadData(&heavyLoadDataContainerServiceHeavyLoadDataServer{stream})
}

type HeavyLoadDataContainerService_HeavyLoadDataServer interface {
	SendAndClose(*HeavyLoadDataResponse) error
	Recv() (*HeavyLoadDataRequest, error)
	grpc.ServerStream
}

type heavyLoadDataContainerServiceHeavyLoadDataServer struct {
	grpc.ServerStream
}

func (x *heavyLoadDataContainerServiceHeavyLoadDataServer) SendAndClose(m *HeavyLoadDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *heavyLoadDataContainerServiceHeavyLoadDataServer) Recv() (*HeavyLoadDataRequest, error) {
	m := new(HeavyLoadDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HeavyLoadDataContainerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HeavyLoadDataContainerService",
	HandlerType: (*HeavyLoadDataContainerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeavyLoadData",
			Handler:       _HeavyLoadDataContainerService_HeavyLoadData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/heavyload.proto",
}
