// Code generated by protoc-gen-go. DO NOT EDIT.
// source: expert/lang-combat/api-proto/protos/login-proto/login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequestData struct {
	EmailOrPhone         string   `protobuf:"bytes,1,opt,name=EmailOrPhone,proto3" json:"EmailOrPhone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequestData) Reset()         { *m = LoginRequestData{} }
func (m *LoginRequestData) String() string { return proto.CompactTextString(m) }
func (*LoginRequestData) ProtoMessage()    {}
func (*LoginRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_38beeb18d9224651, []int{0}
}

func (m *LoginRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequestData.Unmarshal(m, b)
}
func (m *LoginRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequestData.Marshal(b, m, deterministic)
}
func (m *LoginRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequestData.Merge(m, src)
}
func (m *LoginRequestData) XXX_Size() int {
	return xxx_messageInfo_LoginRequestData.Size(m)
}
func (m *LoginRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequestData proto.InternalMessageInfo

func (m *LoginRequestData) GetEmailOrPhone() string {
	if m != nil {
		return m.EmailOrPhone
	}
	return ""
}

func (m *LoginRequestData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponseData struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponseData) Reset()         { *m = LoginResponseData{} }
func (m *LoginResponseData) String() string { return proto.CompactTextString(m) }
func (*LoginResponseData) ProtoMessage()    {}
func (*LoginResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_38beeb18d9224651, []int{1}
}

func (m *LoginResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponseData.Unmarshal(m, b)
}
func (m *LoginResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponseData.Marshal(b, m, deterministic)
}
func (m *LoginResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponseData.Merge(m, src)
}
func (m *LoginResponseData) XXX_Size() int {
	return xxx_messageInfo_LoginResponseData.Size(m)
}
func (m *LoginResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponseData proto.InternalMessageInfo

func (m *LoginResponseData) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *LoginResponseData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type LoginRequest struct {
	LoginRequestData     *LoginRequestData `protobuf:"bytes,1,opt,name=loginRequestData,proto3" json:"loginRequestData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38beeb18d9224651, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLoginRequestData() *LoginRequestData {
	if m != nil {
		return m.LoginRequestData
	}
	return nil
}

type LoginResponse struct {
	LoginResponseData    *LoginResponseData `protobuf:"bytes,1,opt,name=loginResponseData,proto3" json:"loginResponseData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38beeb18d9224651, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetLoginResponseData() *LoginResponseData {
	if m != nil {
		return m.LoginResponseData
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequestData)(nil), "login.LoginRequestData")
	proto.RegisterType((*LoginResponseData)(nil), "login.LoginResponseData")
	proto.RegisterType((*LoginRequest)(nil), "login.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "login.LoginResponse")
}

func init() {
	proto.RegisterFile("expert/lang-combat/api-proto/protos/login-proto/login.proto", fileDescriptor_38beeb18d9224651)
}

var fileDescriptor_38beeb18d9224651 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xa9, 0xd0, 0xaa, 0x63, 0x85, 0x36, 0x07, 0x0d, 0x9e, 0x24, 0x27, 0x2f, 0x6d, 0x40,
	0x8f, 0x1e, 0xb5, 0x9e, 0x04, 0x4b, 0xf6, 0xe0, 0x79, 0xba, 0x86, 0xba, 0x90, 0x4d, 0x62, 0x26,
	0x8b, 0x7e, 0x7c, 0x71, 0x8c, 0x7f, 0x76, 0xf7, 0x12, 0xde, 0x9b, 0x61, 0x7e, 0xbc, 0x17, 0xb8,
	0xb5, 0x1f, 0xd1, 0xa6, 0xac, 0x1d, 0xfa, 0xfd, 0xaa, 0x0e, 0xed, 0x0e, 0xb3, 0xc6, 0xd8, 0xac,
	0x62, 0x0a, 0x39, 0x68, 0x7e, 0x49, 0xbb, 0xb0, 0x6f, 0x7c, 0x19, 0xb1, 0x5e, 0xb3, 0x16, 0x53,
	0x36, 0xca, 0xc0, 0xe2, 0xf1, 0x4b, 0x18, 0xfb, 0xd6, 0x59, 0xca, 0xf7, 0x98, 0x51, 0x28, 0x98,
	0x6f, 0x5a, 0x6c, 0xdc, 0x53, 0xda, 0xbe, 0x06, 0x6f, 0xe5, 0xe4, 0x72, 0x72, 0x75, 0x6c, 0x7a,
	0x33, 0x71, 0x01, 0x47, 0x5b, 0x24, 0x7a, 0x0f, 0xe9, 0x45, 0x1e, 0xf0, 0xfe, 0xd7, 0xab, 0x0d,
	0x2c, 0x0b, 0x93, 0x62, 0xf0, 0x64, 0x19, 0x2a, 0xe1, 0xb0, 0xea, 0xea, 0xda, 0x12, 0x15, 0xde,
	0x8f, 0x15, 0x67, 0x30, 0xab, 0x32, 0xe6, 0x8e, 0x18, 0x34, 0x35, 0xc5, 0xa9, 0x0a, 0xe6, 0xff,
	0xa3, 0x89, 0x3b, 0x58, 0xb8, 0x41, 0x54, 0x46, 0x9d, 0x5c, 0x9f, 0xaf, 0xbf, 0x9b, 0x0d, 0x9b,
	0x98, 0xd1, 0x81, 0x7a, 0x86, 0xd3, 0x5e, 0x36, 0xf1, 0x00, 0x4b, 0x37, 0x0c, 0x5b, 0xb0, 0xb2,
	0x8f, 0xfd, 0xdb, 0x9b, 0xf1, 0xc9, 0x6e, 0xc6, 0xdf, 0x7a, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff,
	0xda, 0x70, 0x15, 0xc9, 0x95, 0x01, 0x00, 0x00,
}
