// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oauth2/proto/oauth.proto

package oauthpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d4d561618ed14d6, []int{0}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CommonResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type OAuthRequest struct {
	GoogleAccessToken    string   `protobuf:"bytes,1,opt,name=google_access_token,json=googleAccessToken,proto3" json:"google_access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthRequest) Reset()         { *m = OAuthRequest{} }
func (m *OAuthRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthRequest) ProtoMessage()    {}
func (*OAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d4d561618ed14d6, []int{1}
}

func (m *OAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthRequest.Unmarshal(m, b)
}
func (m *OAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthRequest.Marshal(b, m, deterministic)
}
func (m *OAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthRequest.Merge(m, src)
}
func (m *OAuthRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthRequest.Size(m)
}
func (m *OAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthRequest proto.InternalMessageInfo

func (m *OAuthRequest) GetGoogleAccessToken() string {
	if m != nil {
		return m.GoogleAccessToken
	}
	return ""
}

type OAuthResponse struct {
	CommonResponse       *CommonResponse `protobuf:"bytes,1,opt,name=commonResponse,proto3" json:"commonResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OAuthResponse) Reset()         { *m = OAuthResponse{} }
func (m *OAuthResponse) String() string { return proto.CompactTextString(m) }
func (*OAuthResponse) ProtoMessage()    {}
func (*OAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d4d561618ed14d6, []int{2}
}

func (m *OAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthResponse.Unmarshal(m, b)
}
func (m *OAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthResponse.Marshal(b, m, deterministic)
}
func (m *OAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthResponse.Merge(m, src)
}
func (m *OAuthResponse) XXX_Size() int {
	return xxx_messageInfo_OAuthResponse.Size(m)
}
func (m *OAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthResponse proto.InternalMessageInfo

func (m *OAuthResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonResponse)(nil), "oauth.CommonResponse")
	proto.RegisterType((*OAuthRequest)(nil), "oauth.OAuthRequest")
	proto.RegisterType((*OAuthResponse)(nil), "oauth.OAuthResponse")
}

func init() { proto.RegisterFile("oauth2/proto/oauth.proto", fileDescriptor_8d4d561618ed14d6) }

var fileDescriptor_8d4d561618ed14d6 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xd0, 0x96, 0x8c, 0x5a, 0x71, 0xab, 0x12, 0x3c, 0x95, 0x9c, 0x7a, 0x4a, 0x21,
	0x5e, 0x55, 0x68, 0x3d, 0x78, 0x11, 0x85, 0xd5, 0x93, 0x97, 0xb2, 0x5d, 0x86, 0x54, 0x34, 0x99,
	0xd8, 0x99, 0xf5, 0xf7, 0x8b, 0x93, 0x15, 0x5c, 0x6f, 0xfb, 0xde, 0xdb, 0xf7, 0xf8, 0x76, 0xa1,
	0x20, 0x17, 0x64, 0x57, 0x2f, 0xfb, 0x3d, 0x09, 0x2d, 0x55, 0x54, 0x7a, 0x36, 0x23, 0x15, 0xe5,
	0x1a, 0xa6, 0x77, 0xd4, 0xb6, 0xd4, 0x59, 0xe4, 0x9e, 0x3a, 0x46, 0x73, 0x01, 0x63, 0x16, 0x27,
	0x81, 0x8b, 0x6c, 0x9e, 0x2d, 0x46, 0x36, 0x2a, 0x53, 0xc0, 0xa4, 0x45, 0x66, 0xd7, 0x60, 0x71,
	0x30, 0xcf, 0x16, 0xb9, 0xfd, 0x95, 0xe5, 0x2d, 0x1c, 0x3d, 0xad, 0x82, 0xec, 0x2c, 0x7e, 0x06,
	0x64, 0x31, 0x15, 0xcc, 0x1a, 0xa2, 0xe6, 0x03, 0x37, 0xce, 0x7b, 0x64, 0xde, 0x08, 0xbd, 0x63,
	0xa7, 0x73, 0xb9, 0x3d, 0x1d, 0xa2, 0x95, 0x26, 0x2f, 0x3f, 0x41, 0xf9, 0x08, 0xc7, 0xb1, 0x1f,
	0x11, 0x6e, 0x60, 0xea, 0x13, 0x28, 0xed, 0x1e, 0xd6, 0xe7, 0xd5, 0xf0, 0x82, 0x94, 0xd8, 0xfe,
	0xbb, 0x5c, 0x3f, 0x44, 0x9e, 0x67, 0xdc, 0x7f, 0xbd, 0x79, 0x34, 0xd7, 0x70, 0x72, 0x8f, 0x92,
	0x58, 0xb3, 0xb8, 0xf4, 0x97, 0xfb, 0xf2, 0x2c, 0x35, 0x87, 0xb5, 0x75, 0xfe, 0x3a, 0x51, 0xbb,
	0xdf, 0x6e, 0xc7, 0xfa, 0x75, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x2a, 0x1b, 0xef,
	0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OAuthServiceClient is the client API for OAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OAuthServiceClient interface {
	GetOAuthService(ctx context.Context, in *OAuthRequest, opts ...grpc.CallOption) (*OAuthResponse, error)
}

type oAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewOAuthServiceClient(cc *grpc.ClientConn) OAuthServiceClient {
	return &oAuthServiceClient{cc}
}

func (c *oAuthServiceClient) GetOAuthService(ctx context.Context, in *OAuthRequest, opts ...grpc.CallOption) (*OAuthResponse, error) {
	out := new(OAuthResponse)
	err := c.cc.Invoke(ctx, "/oauth.OAuthService/GetOAuthService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthServiceServer is the server API for OAuthService service.
type OAuthServiceServer interface {
	GetOAuthService(context.Context, *OAuthRequest) (*OAuthResponse, error)
}

func RegisterOAuthServiceServer(s *grpc.Server, srv OAuthServiceServer) {
	s.RegisterService(&_OAuthService_serviceDesc, srv)
}

func _OAuthService_GetOAuthService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).GetOAuthService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.OAuthService/GetOAuthService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).GetOAuthService(ctx, req.(*OAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oauth.OAuthService",
	HandlerType: (*OAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOAuthService",
			Handler:    _OAuthService_GetOAuthService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth2/proto/oauth.proto",
}
